### ISSUE TITLE
quizID still undefined

### ISSUE THREAD

**Issue by js802025** [theusaf/kahoot.js-updated#13]
I don't exactly know if this is my fault or the codes I downloaded the repo and put it into node_modules, yet the quizID still says undefined. Here is the whole quizfinishevent class:
QuizFinishEvent {
  client: Kahoot {
    _events: [Object: null prototype] {
      quizStart: [Function],
      question: [Function],
      questionStart: [Function],
      questionSubmit: [Function],
      questionEnd: [Function],
      finishText: [Function],
      finish: [Function]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    _wsHandler: WSHandler {
      _events: [Object: null prototype],
      _eventsCount: 13,
      _maxListeners: undefined,
      requires2Step: false,
      finished2Step: false,
      kahoot: [Circular],
      msgID: 14,
      clientID: '7k0f11ls2m5m7k581c1v6sd9k7kumie',
      connected: true,
      gameID: 9903243,
      name: 'kahoot.js',
      firstQuizEvent: true,
      lastReceivedQ: null,
      ws: [WebSocket],
      dataHandler: [Object],
      timesync: [Object],
      ready: true
    },
    _qFulfill: [Function],
    sendingAnswer: false,
    token: '0d9557b8024e250fb032a827b88bacc9e083ddc6bcea72a9bc7aad447513f02925ce811e7bcba70cc12877435549dbc0',
    sessionID: 9903243,
    name: 'kahoot.js',
    quiz: Quiz {
      client: [Circular],
      name: '7*2',
      type: 'quiz',
      answerCount: 4,
      currentQuestion: [Question],
      questions: [Array],
      questionCount: 1,
      answerCounts: undefined
    },
    nemesis: Nemesis {
      name: null,
      id: null,
      score: null,
      isKicked: null,
      exists: false
    },
    nemeses: [ [Nemesis] ],
    totalScore: 0,
    gamemode: 'classic',
    cid: '474520034',
    team: undefined
  },
  quiz: Quiz {
    client: Kahoot {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _wsHandler: [WSHandler],
      _qFulfill: [Function],
      sendingAnswer: false,
      token: '0d9557b8024e250fb032a827b88bacc9e083ddc6bcea72a9bc7aad447513f02925ce811e7bcba70cc12877435549dbc0',
      sessionID: 9903243,
      name: 'kahoot.js',
      quiz: [Circular],
      nemesis: [Nemesis],
      nemeses: [Array],
      totalScore: 0,
      gamemode: 'classic',
      cid: '474520034',
      team: undefined
    },
    name: '7*2',
    type: 'quiz',
    answerCount: 4,
    currentQuestion: Question {
      client: [Kahoot],
      quiz: [Circular],
      index: 0,
      timeLeft: 5,
      type: 'quiz',
      usesStoryBlocks: undefined,
      ended: true,
      number: 1
    },
    questions: [ [Question] ],
    questionCount: 1,
    answerCounts: undefined
  },
  players: 1,
  quizID: undefined,
  rank: 1,
  correct: 0,
  incorrect: 1
}

**Comment by theusaf** [comment]
Alright, I fixed it. I just tested it and the quiz id now shows. Enjoy!
