### ISSUE TITLE
kahoot updated their system again

### ISSUE THREAD

**Issue by Centipede5** [theusaf/kahoot.js-updated#16]
I just started getting this error today: 

`request error: { Error: socket hang up `

did kahoot change their system again?

**Comment by theusaf** [comment]
Looks like your PR fixed it! Thanks :)

**Comment by Linux4win** [comment]
> Looks like your PR fixed it! Thanks :)
Do you mean to say that the bug is fixed? The issue is closed...

**Comment by theusaf** [comment]
Yes, the bug is fixed

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir
