### ISSUE TITLE
Why `var me = this`?

### ISSUE THREAD

**Issue by adroitwhiz** [theusaf/kahoot.js-updated#21]
At the top of most functions, there's this statement:
```js
var me = this;
```

I can't seem to figure out why this is being done.

It's a [common pattern to preserve the original value of `this` inside function expressions](https://stackoverflow.com/questions/962033/what-underlies-this-javascript-idiom-var-self-this), but this codebase uses arrow functions, which [don't bind their own value of `this`](https://hackernoon.com/javascript-es6-arrow-functions-and-lexical-this-f2a3e2a5e8c4), so I'm not sure why it's necessary.

**Comment by theusaf** [comment]
It’s just a habit that was used by the original creator which I have adopted. Sometimes, I still do that just in case. It doesn’t seem to be affecting the program though.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir
