### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by JeroenoBoy** [theusaf/kahoot.js-updated#23]
The bot doesn't work anymore, I think Kahoot updated their servers.

Edit: the bots do join but don't answer anymore

**Comment by theusaf** [comment]
Which version of kahoot.js-updated are you using? From my testing, the bots still join and answer.
However, I can confirm that it doesn't answer sometimes. If the bot immediately answers the kahoot, it will not be sent through. However, adding a small timeout resolves this issue.

Possible Solutions:
- Add a 0.5-second timeout to answering the question to your code.
- Check when the question starts, and send the answer only when question.answer() is called after a certain amount of time.

**Comment by JeroenoBoy** [comment]
Using the latest, but il use a small delay in that case
