### ISSUE TITLE
Best Way to Join with Multiple Bots

### ISSUE THREAD

**Issue by 4424dev** [theusaf/kahoot.js-updated#24]
Hi, I am currently utilizing your NPM package. It works nice, thank you for making it. However I am stuck at how to add multiple bots. I am currently using a `for` loop but it is broken in the latest update, as it sometimes doesn't join and doesn't answer if it does.

**Comment by JeroenoBoy** [comment]
Hi, the magic thing is this:

**Comment by JeroenoBoy** [comment]
Hi 4424dev, so this is what you need to do:

**Comment by JeroenoBoy** [comment]
Hi 4424dev, so this is what you need to do:

`js
//ofc first require the bot
const Kahoot = require('kahoot.js-updated');

//Variables for sessions etc
let session = 1234567 //kahoot id
let name = 'random name';

//the loop
for(let i = 0; i < 50; i++) {
	let bot = new Kahoot;
	bot.client.join(session, name+'-'+i)
}
`

**Comment by theusaf** [comment]
As JeronoBoy said, that is how you would send a bunch of bots. Though I think you know that already. There is also a howmany.js test file in /tests. So far, I am not able to replicate being unable to answer or join, which I thought I fixed in 1.2.11. Are you sure you are using the latest version?

**Comment by theusaf** [comment]
Another possible reason could be that Kahoot has DDOS protection, sending an error page when too many bots are connected from the same IP.

**Comment by JeroenoBoy** [comment]
Oh, yeah the answer worked with the delay

**Comment by Helixable** [comment]
> Another possible reason could be that Kahoot has DDOS protection, sending an error page when too many bots are connected from the same IP.

How could you variate the IP?

**Comment by theusaf** [comment]
You would need access to various proxies/servers. If you have multiple servers, you can create scripts to listen for web requests in each server, and then use kahoot.js-updated to connect to Kahoot.

If you want to use proxies, you would have to modify the code to use the proxy in token.js

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir

**Comment by theusaf** [comment]
In version 2, this is now a bit easier to do through the `proxy` and `proxyws` options.
