### ISSUE TITLE
Add support for proxies

### ISSUE THREAD

**Issue by theusaf** [theusaf/kahoot.js-updated#25]
**Is your feature request related to a problem? Please describe.**
This feature request is related to #24, #19, and #18.

**Describe the solution you'd like**
Add support for proxies in token.js as a configurable option.

**Comment by theusaf** [comment]
Needs a bit of tweaking, but it works

**Comment by JeroenoBoy** [comment]
Proxies don't work?
I just randomly downloaded a list from https://openproxy.space/generator, but none seemed to work with this? (they do work with curl cmd etc), do you have any recommended way of getting proxies, or is it some kind of bug in the code?

**Comment by theusaf** [comment]
How would you use that proxy? Currently, the proxy just works with GET requests, and works by appending the proxy URL in front of the kahoot URL:
GET http://142.92.114.42:8080/https://kahoot.it/reserve/session/foo/<?current date>

**Comment by JeroenoBoy** [comment]
Alrighty, too bad
