### ISSUE TITLE
Logging Mode

### ISSUE THREAD

**Issue by Helixable** [theusaf/kahoot.js-updated#26]
I was trying to use the console for debugging, but the package spits put "sending packet" every time I answer a question. This isn't a problem, but could you add a "logging mode" or something? It could log all the server's responses and more. Mabye have it output the logs into an array or something? 

Thanks!

**Comment by theusaf** [comment]
Yeah, that’s a small issue, where I forgot to remove a console.log statement when debugging. I’ll push the fixed version later.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir

**Comment by theusaf** [comment]
I’ll consider adding a logging mode as a config option. Thanks for the suggestion

**Comment by Helixable** [comment]
Np. You should try making an unofficial Quizlet API. I could help out here and there.

**Comment by theusaf** [comment]
Thinking about making gimkit / quizlet / quizziz apis, but no time currently. I’ll notify you when I start on it.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir

**Comment by Helixable** [comment]
Got it.

**Comment by JeffaloBob** [comment]
notify me if you can :)

im using this package in my kahoot bot and its a charm :)
