### ISSUE TITLE
Private Kahoot Answers

### ISSUE THREAD

**Issue by Helixable** [theusaf/kahoot.js-updated#28]
Suggestion: Find a way to extract answers for private Kahoots. And I don't mean `question.correctAnswer`. Something that gets the answers before hand. There's gotta be some data you can get through the websockets.
I already have a script that gets public kahoot answers.

**Comment by theusaf** [comment]
Kahoot does not send anything that allows you to access private Kahoots. In order for that to work, you would need to guess the hosts username and password, which, maybe the username is sent, but guessing a password is hard [citation needed]. Even if you get the uuid of the quiz, Kahoot will respond with an unauthorized response if you aren’t logged in. I too, also have a website for public quizzes.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir

**Comment by theusaf** [comment]
https://play.kahoot.it/v2/assets/js/vendors~main.5def6c12.chunk.js
https://play.kahoot.it/v2/assets/js/main.1fa76800.chunk.js

These are the files that Kahoot quizzes use to send and receive messages. If you find something here that makes it respond with the quiz data, then this is possible. Otherwise, as I suspect, you cannot get the data of a private Kahoot.

**Comment by Helixable** [comment]
Another thing. How do you find all the REST endpoints of websites like Kahoot and stuff?

**Comment by theusaf** [comment]
I use the chrome dev tools, and look at the network tab to see what the webpage is getting.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir

**Comment by Helixable** [comment]
Thanks

**Comment by JeroenoBoy** [comment]
> Suggestion: Find a way to extract answers for private Kahoots. And I don't mean `question.correctAnswer`. Something that gets the answers before hand. There's gotta be some data you can get through the websockets.
> I already have a script that gets public kahoot answers.

It IS possible to do this, the way I did it is by using @theusaf 's Kahoot search API, although it can be easily fixed by the Kahoot hoster if they randomize questions or answers, but most teachers don't know this option even exists.

**Comment by theusaf** [comment]
The Kahoot search API doesn't show private kahoots.

**Comment by theusaf** [comment]
Closing because no methods to get private kahoots have been found.
