### ISSUE TITLE
Not Compatible with the "jumble" mode on kahoot

### ISSUE THREAD

**Issue by FarhanRehman** [theusaf/kahoot.js-updated#3]

**Comment by theusaf** [comment]
Confirmed. On to-do list.

**Comment by theusaf** [comment]
From my testing, I could not replicate this issue. Please provide some evidence. Perhaps, you may just be confusing the error with [#2](https://github.com/theusaf/kahoot.js-updated/issues/2)?

**Comment by FarhanRehman** [comment]
var Kahoot = require("kahoot.js-updated");
var client = new Kahoot;
console.log("Joining kahoot...");
client.join(161153 /* Or any other kahoot game pin */, "kahoot.js");
client.on("joined", () => {
    console.log("I joined the Kahoot!");
});
client.on("quizStart", quiz => {
    console.log("The quiz has started! The quiz's name is:", quiz.name);
});
client.on("questionStart", question => {
    console.log("A new question has started, answering the first answer.");
    question.answer(0);
});
client.on("quizEnd", () => {
    console.log("The quiz has ended.");
});

**Comment by theusaf** [comment]
For jumbles, use arrays for the answer rather than a number:
jumble: question.answer([0,1,2,3]);
quiz: question.answer(0);
This is because jumbles require players to put in steps of answers and organize phrases to make the final answer.

**Comment by FarhanRehman** [comment]
Yeah, I added that and now although it is answering the questions its consistently getting the answer wrong.

`
var Kahoot = require("kahoot.js-updated");
var client = new Kahoot;
console.log("Joining kahoot...");
client.join(654156 /* Or any other kahoot game pin */, "F");
client.on("joined", () => {
    console.log("I joined the Kahoot!");
});
client.on("quizStart", quiz => {
    console.log("The quiz has started! The quiz's name is:", quiz.name);
});
client.on("questionStart", question => {
    console.log("A new question has started, answering the first answer.");
     question.answer([0,1,2,3]);
});
client.on("quizEnd", () => {
    console.log("The quiz has ended.");
});
`

**Comment by FarhanRehman** [comment]
Yeah, I added that and although it answers the questions it doesn't get it the answer correct.

var Kahoot = require("kahoot.js-updated");
var client = new Kahoot;
const PIN = "654156";
console.log("joining game...");
client.join(PIN, "F");
client.on("joined", () => {
    console.log("joined the game. waiting for quiz to start");
});
client.on("quiz", quiz => {
	// List all the properties of a quiz
	console.log("quiz has started. properties:");
	console.log("name: " + quiz.name);
	console.log("type: " + quiz.type);
	console.log("answercount: " + quiz.answerCount);
	console.log("currentQuestion: " + quiz.currentQuestion);
});
client.on("question", q => {
	console.log("question recieved. properties:");
	console.log("index: " + q.index);
	console.log("timeLeft: "+ q.timeLeft);
	console.log("type: " + q.type);
	console.log("usesStoryBlocks: " + q.usesStoryBlocks);
	console.log("ended: " + q.ended);
	console.log("number: " + q.number);
});
client.on("questionStart", q => {
	console.log("question started.");
	q.answer([0,1,2,3]); // answer to be able to recieve the questionSubmit event
});
client.on("questionEnd", e => {
	console.log("question ended. event properties:");
	console.log("text: " + e.text);
	console.log("correctAnswers: " + e.correctAnswers);
	console.log("nemisis: " + e.nemisis);
	console.log("correct: " + e.correct);
	console.log("ended: " + e.question.ended);
});
client.on("questionSubmit", e => {
	console.log("question submitted. event properties: ");
	console.log(e.message);
	console.log(e.question);
});
client.on("finishText", e => {
	console.log("got finishText event, properties:");
	console.log(e.messages);
	console.log(e.metal);
});
client.on("finish", e => {
	console.log("finished, event properties:");
	console.log("players: " + e.players);
	console.log("quizID: " + e.quizID);
	console.log("rank: " + e.rank);
	console.log("correct: " + e.correct);
	console.log("incorrect: " + e.incorrect);
})

**Comment by theusaf** [comment]
Yes, which is probably due to the fact that it was incorrect. I just tested it myself, and it worked. (I used the readline interface to put custom user data, so I could answer it correctly).
