### ISSUE TITLE
Proxies not fully supported

### ISSUE THREAD

**Issue by vektrix1** [theusaf/kahoot.js-updated#33]
**Describe the bug**
I have a list of proxies I tested and am sure work, but don't in kahoot.js.

**To Reproduce**
Try to join a kahoot game using an http proxy

**Expected behavior**
The bot joins the game normally

**System (please complete the following information):**
macOS 10.15.4 Beta

**Comment by theusaf** [comment]
Previously noted in #25. Proxies do work, but only in specific ways.

**Comment by vektrix1** [comment]
the proxies I am using are the specified type (http) where you append the kahoot url to the end. But I see it only works for GET requests. I'll try and read up on the source to add support for other types of requests

**Comment by theusaf** [comment]
Should be fixed? You can specify more options now (including method). Comment if it still doesn't work.
