### ISSUE TITLE
Support for Kahoot challenges.

### ISSUE THREAD

**Issue by theusaf** [theusaf/kahoot.js-updated#35]
**Describe the solution you'd like**
Add functionality to play Kahoot challenges
- Should allow input to be customized (such as the timing of answer, etc.)
- Should still use mostly the same API as before
- More options to automatically progress or not
- Should not break anything in the challenge

**Comment by theusaf** [comment]
or should this be a different module?

**Comment by js802025** [comment]
I think it would be great as part of this module.

**Comment by theusaf** [comment]
1.4.0 is out, use `npm i kahoot.js-updated@prerelease`
- needs more testing
  - testing multiple_select_quiz
  - testing skipping questions
  - testing custom points
  - testing rejoining
