### ISSUE TITLE
is there any way that i could get kahoot.win source code?

### ISSUE THREAD

**Issue by nikidziuba** [theusaf/kahoot.js-updated#36]
I dont know where else to post it so yeah...

**Comment by theusaf** [comment]
By “kahoot.win,” do you mean https://kahoot-win.herokuapp.com ? Currently, I have no plans to release the source code for that website, but you can visit https://kahoot-win.herokuapp.com/how-it-works to get a general idea of the code.

**Comment by nikidziuba** [comment]
Yeah, that that was what i meant. Thanks for answering!

czw., 7 maj 2020 o 07:07 theusaf <notifications@github.com> napisał(a):
