### ISSUE TITLE
no bots are joining

### ISSUE THREAD

**Issue by JeffaloBob** [theusaf/kahoot.js-updated#41]
**Describe the bug**
code that used to work to join bots no longer works. no errors are thrown, no console.logs. it just doesn't join the kahoot.

**To Reproduce**
1. send bots to kahoot
2. see nothing
3. see no users
4. sad

**Expected behavior**
bot joins kahoot as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/40470736/82573057-93bfd600-9b85-11ea-9a2c-b7fd2f7691fe.png)

**System (please complete the following information):**
- windows 10
- running with nodejs

**Additional context**
it used to work in my project kahoot-gui but that doesn't seem to work either

**Comment by theusaf** [comment]
I was able to successfully connect to the game using tests/join_leave.js

Do you have any code that you can provide? When you encountered this issue, were you running your code on your own computer, or from a server that has been sending bots often?

**Comment by JeffaloBob** [comment]
> I was able to successfully connect to the game using tests/join_leave.js
> 
> Do you have any code that you can provide? When you encountered this issue, were you running your code on your own computer, or from a server that has been sending bots often?

i encountered this on my computer and on a repl.it nodejs server.

my code was the example code from npm
```js
var Kahoot = require("kahoot.js-updated");
var client = new Kahoot;
console.log("Joining kahoot...");
client.join(9802345 /* Or any other kahoot game pin */, "kahoot.js");
client.on("joined", () => {
    console.log("I joined the Kahoot!");
});
client.on("quizStart", quiz => {
    console.log("The quiz has started! The quiz's name is:", quiz.name);
});
client.on("questionStart", question => {
    console.log("A new question has started, answering the first answer.");
    question.answer(0);
});
client.on("quizEnd", () => {
    console.log("The quiz has ended.");
});
```

and the more advanced code was from [this mess](https://github.com/JeffaloBob/kahoot-gui)

**Comment by theusaf** [comment]
Example code succeeded on runkit. What version of kahoot.js-updated are you using?

**Comment by JeffaloBob** [comment]
> Example code succeeded on runkit. What version of kahoot.js-updated are you using?

the latest from npm. i ran `npm i kahoot.js-updated`

**Comment by theusaf** [comment]
Strange. Can you add `client.loggingMode = true` before joining a game and tell me what is logged?

**Comment by JeffaloBob** [comment]
```
SND: [{"advice":{"interval":0,"timeout":60000},"channel":"/meta/handshake","ext":{"ack":true,"timesync":{"l":0,"o":0,"tc":1590074749669},"id":"1","minimumVersion":"1.0","supportedConnectionTypes":["websocket","long-polling"],"version":"1.0"}}]
D:\coding projects\newkahoot\node_modules\kahoot.js-updated\src\WSHandler.js:241 SND: [{"advice":{"interval":0,"timeout":60000},"channel":"/meta/handshake","ext":{"ack":true,"timesync":{"l":0,"o":0,"tc":1590074749774},"id":"1","minimumVersion":"1.0","supportedConnectionTypes":["websocket","long-polling"],"version":"1.0"}}]
```

this is what i got

**Comment by theusaf** [comment]
That is all that was logged? Can you host a game and put the pin here?

**Comment by JeffaloBob** [comment]
never mind,
after restarting it just worked. i'm not sure what changed but it seems to work now

**Comment by theusaf** [comment]
Ok. closing.
