### ISSUE TITLE
Cannot find module '/consts.js'

### ISSUE THREAD

**Issue by paulgrasser** [theusaf/kahoot.js-updated#42]
**Describe the bug**
I am using NuxtJS to make a Kahoot Client. When the user tries to join the game, i execute this piece of code:

```
const Kahoot = require('kahoot.js-updated')
const client = new Kahoot()
console.log('Joining kahoot...')
client.join(this.gamePin, this.playerName)
client.on('joined', () => {
  console.log('I joined the Kahoot!')
})
```
But I get this error: 

```
Cannot find module '/consts.js'
    at webpackEmptyContext (eval at ./node_modules/kahoot.js-updated/src sync recursive (index.js:22), <anonymous>:2:10)
    at Object.eval (token.js?16c9:4)
    at eval (token.js:200)
    at Object../node_modules/kahoot.js-updated/src/token.js (index.js:214)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
    at eval (kahoot.js?5a3c:6)
    at Object../node_modules/kahoot.js-updated/src/kahoot.js (index.js:203)
    at __webpack_require__ (runtime.js:854)
    at fn (runtime.js:151)
```

I tried executing the same piece of code on the server side part of my app, and it worked. If I did it like this however it would be tricky to communicate real-time events like new questions to the client. Is it not possible on the client side? If it is, what am I doing wrong?

I am using:
Express                  --> 4.16.4
Kahoot.js-updated  --> 1.4.20
Nuxt                        --> 2.0.0

**Comment by theusaf** [comment]
It seems that it is because `__dirname` acts differently in webpack. Try looking at this: https://codeburst.io/use-webpack-with-dirname-correctly-4cad3b265a92

**Comment by paulgrasser** [comment]
> It seems that it is because `__dirname` acts differently in webpack. Try looking at this: https://codeburst.io/use-webpack-with-dirname-correctly-4cad3b265a92
> 
> As for communicating events in realtime, you could also take a look at web sockets.

In the page the file webpack.config.js is updated. I don't have this file, so I don't think I'm using webpack? Or does Nuxt take care of this for me?

**Comment by theusaf** [comment]
Here are more links that I found, I don't have much knowledge of Nuxt.
https://stackoverflow.com/questions/58141169/dirname-in-nuxt
https://nuxtjs.org/api/configuration-srcdir/#the-srcdir-property

If none of these work, you can update `token.js` by replacing the `path.join(...)` with `./consts.js` instead.

**Comment by paulgrasser** [comment]
Okay, I edited the `token.js` file and now I don't get an error but the client just doesn't manage to connect. I get the console message `Joining kahoot...` but then nothing. It's been trying for the past 2 minutes and I don't think it will make it.

**Comment by theusaf** [comment]
Can you set `client.loggingMode = true` and tell me what logs?

**Comment by paulgrasser** [comment]
Code snippet is now:
```
const Kahoot = require('kahoot.js-updated')
const client = new Kahoot()
client.loggingMode = true
console.log('Joining kahoot...')
client.join(this.gamePin, this.playerName)
client.on('joined', () => {
  console.log('I joined the Kahoot!')
})
```
and there is no new logs.

**Comment by theusaf** [comment]
Hmm, I don't know then. Does NuxtJS create an application, or is this a website in the browser?

**Comment by paulgrasser** [comment]
It's a website

**Comment by theusaf** [comment]
Then its probably because web browsers won't allow the cross-origin requests for the token or the WebSocket. This can be confirmed if there is a developer tool for the browser and watching the 'network' tab. 
```js
const Kahoot = require('kahoot.js-updated')
const client = new Kahoot()
client.loggingMode = true
console.log('Joining kahoot...')
client.join(this.gamePin, this.playerName).catch(err=>{
  console.log(err); // should probably be "token_error"
});
client.on('joined', () => {
  console.log('I joined the Kahoot!')
})
```

**Comment by paulgrasser** [comment]
Ah, now I get something:
```
TypeError: URL is not a constructor
    at Function.requestToken (token.js?16c9:26)
    at Function.resolve (token.js?16c9:119)
    at eval (kahoot.js?5a3c:128)
    at tryCallTwo (core.js?bd2d:45)
    at doResolve (core.js?bd2d:200)
    at new Promise (core.js?bd2d:66)
    at Kahoot.join (kahoot.js?5a3c:116)
    at VueComponent.joinGame (VM9375 index.vue:85)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at HTMLDivElement.invoker (vue.runtime.esm.js?2b0e:2179)
```

**Comment by theusaf** [comment]
That error doesn't seem like something I can fix. (URL is supposed to be a built-in Node.js class) I would suggest doing all the Kahoot bot stuff on the server and use WebSockets for real-time communication with clients. Websites are not the same as servers and cannot run all Node.js programs

**Comment by paulgrasser** [comment]
Alright, do you have a good site to check out these websockets?

**Comment by theusaf** [comment]
https://www.npmjs.com/package/ws is a good package that I use. WebSockets are also built in to browsers: https://developer.mozilla.org/en-US/docs/Web/API/WebSocket

**Comment by paulgrasser** [comment]
Alright, thanks!
