### ISSUE TITLE
2 2Step events in docs?

### ISSUE THREAD

**Issue by Merrick919** [theusaf/kahoot.js-updated#46]
>` on('2Step')`
> 
> - Emitted when the 2 Step Auth is recieved
> - Emitted when the 2 Step Auth is refreshed
> 
> `on('2Step')`
> 
> - Emitted when the 2 Step Auth is correct

So which is which? Are they supposed to be the same?

Edit: realised I didn't get the event because of a typo

**Comment by theusaf** [comment]
The second should have been `on('2StepSuccess)`. Thanks for the report!
