### ISSUE TITLE
If multiple bots are answering, only 100 answer, not the specified amount

### ISSUE THREAD

**Issue by respecting** [theusaf/kahoot.js-updated#56]
**Describe the bug**
If multiple bots are answering, only 100 answer, not the specified amount. For example, 250 people are in a game and they answer randomly. Only 100 bots answer.

**To Reproduce**
1. Go to [here](https://github.com/respecting/kahoot-bot/tree/web)
2. Clone repository
3. Install modules
4. `node flood.js`
5. Go to [here](http://localhost:3278)
6. Flood a server and start kahoot
7. Bug occurs

**Expected behavior**
All bots should answer.

**System (please complete the following information):**
 - macOS Catalina
 - Version 2.0.10

**Comment by theusaf** [comment]
This issue is likely not an issue with `kahoot.js-updated`. Kahoot probably limits the number of answers from a single IP to a single game, which is what is causing this issue. Also, the links provided in the issue are using an outdated version of `kahoot.js-updated`.

**Comment by respecting** [comment]
Ok
