### ISSUE TITLE
Examples don't work 

### ISSUE THREAD

**Issue by gaskraank** [theusaf/kahoot.js-updated#6]
Hi, 
thanks for making this project!

I don't get It working and always get this error Message:

Joining kahoot...
buffer.js:207
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:207:11)
    at new Buffer (buffer.js:182:17)
    at Function.decodeBase64 (/Users/jimmy/Projects/kahoot_updated/node_modules/kahoot.js/src/token.js:54:10)
    at me.requestToken (/Users/jimmy/Projects/kahoot_updated/node_modules/kahoot.js/src/token.js:69:22)
    at IncomingMessage.res.on.chunk (/Users/jimmy/Projects/kahoot_updated/node_modules/kahoot.js/src/token.js:28:6)
    at IncomingMessage.emit (events.js:198:13)
    at IncomingMessage.Readable.read (_stream_readable.js:504:10)
    at flow (_stream_readable.js:973:34)
    at resume_ (_stream_readable.js:954:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Could somebody help me with that? I had a valid session pin ! Greetings.

**Comment by theusaf** [comment]
Unable to reproduce. Are you using the current version 1.1.7? What Node version are you using?

**Comment by gaskraank** [comment]
Hi, thanks for the fast answer.
I have the latest node installed its version : 10.16.3
Also I installed the package with the following command:
nom install Kahoot.js-updated
Thank you very much.

**Comment by gaskraank** [comment]
```
var Kahoot = require('kahoot.js');
var k = new Kahoot;
console.log("Joining kahoot...");
k.join(0700376 /* Or any other kahoot token */, "kahoot.js").then(() => {
	k.on("quizStart", quiz => {
    	console.log("the quiz started with name", quiz.name);
	});
	k.on("questionStart", question => {
	    console.log("A new question has started, answering the first answer.");
	    question.answer(0);
	});
	k.on("questionEnd", event => {
		console.log('the question ended.');
		if (k.nemesis && k.nemesis.exists) {
			console.log('i have a nemesis with name', nemesis.name);
		} else {
			console.log('i dont have a nemesis.');
		}
	});
	k.on("quizEnd", () => {
	    console.log("the quiz ended");
	});
});
```

My Code snippet.

**Comment by theusaf** [comment]
Hmm, it looks like your package is using the old kahoot.js package by wwwg.
Make sure you are installing `kahoot.js-updated` and not `kahoot.js`
- kahoot.js is no longer being maintained, which is why I created kahoot.js-updated

If you have done so already, try this code instead:
`var Kahoot = require('kahoot.js-updated');
var k = new Kahoot;
console.log("Joining kahoot...");
k.join(0700376 /* Or any other kahoot token */, "kahoot.js").then(() => {
	k.on("quizStart", quiz => {
    	console.log("the quiz started with name", quiz.name);
	});
	k.on("questionStart", question => {
	    console.log("A new question has started, answering the first answer.");
	    question.answer(0);
	});
	k.on("questionEnd", event => {
		console.log('the question ended.');
		if (k.nemesis && k.nemesis.exists) {
			console.log('i have a nemesis with name', nemesis.name);
		} else {
			console.log('i dont have a nemesis.');
		}
	});
	k.on("quizEnd", () => {
	    console.log("the quiz ended");
	});
});`

**Comment by gaskraank** [comment]
Reinstalled everything and used your code, worked for me thanks! 

How can I send an answer in a session ? 

Greets & Thanks

**Comment by theusaf** [comment]
You can answer questions by:
session.on("questionStart",q=>{
    q.answer(0);
});
