### ISSUE TITLE
How to get answers of a kahoot question

### ISSUE THREAD

**Issue by codergautam** [theusaf/kahoot.js-updated#60]
so how to get answer of current kahoot question.
i have joined the bot in game but how to answer the question correctly?
i have looked through thedocs but didnt find
here my code

    const kahootJS = require("kahoot.js-updated");
    const bot = new kahootJS();
    var pin = "somepin"
    bot.join(pin, "Coder bot"); 
    bot.on("questionStart", question => {
    //here get corect answer and answerthe question
      question.answer();
    });

**Comment by theusaf** [comment]
To answer the question correctly, you will need to do a lot more complicated things.

Basically: Get the quiz name/id/author from the user and the fetching the quiz, then answering correctly.

If you have fetched the quiz based on the users input, you would do something like this:

const choices = quiz.questions[question.questionIndex].choices;
for(let i in choices){
  if(choices[i].correct){
    var answer = i;
    break;
  }
}
bot.answer(answer);

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir

**Comment by codergautam** [comment]
Hm, ok... But how do you get the quiz object...
Is there a way to fetch the quiz?

**Comment by theusaf** [comment]
I literally answered your two questions in the previous reply.

In Kahoot! challenges, you can get the quiz object in `bot.quiz` or `bot.challengeData`

In public live games, you need to ask the user for the quiz name and use something like `kahoot-search` to search for quizzes.

**Comment by codergautam** [comment]
Mk, thx for help

**Comment by adfhsakfhas** [comment]
@codergautam did u figure this out and by that I mean figure out how to use what you get from the quiz object and input into kahoot-search and it work most of the time
Thanks in advance
