### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by adfhsakfhas** [theusaf/kahoot.js-updated#64]
Ok hi

I respect your work and think its amazing 
anyway I need your help I for some reason can't find how to get the correct answer for each question or even any question
pls give an example and dont judge me this is me first JS project

Thanks in advance also I saw your Kahoot winner thing nice.

**Comment by adfhsakfhas** [comment]
its not a bug I am just stoopid lol

**Comment by adfhsakfhas** [comment]
pls I am trying to and no joke i have been on this for hours, tho it looks like 30 min i havent asked since then also i am making it flood bots that get all right answers so u know the bots are down but uhhh maybe u wanna see my code its not good by any standard

this is code sorry for it not be syntaxed highlighted its just well i couldn't upload a js file
[app - Copy.txt](https://github.com/theusaf/kahoot.js-updated/files/5564142/app.-.Copy.txt)

**Comment by adfhsakfhas** [comment]
u can rename it to app.js for u and it will be highlighted in ur editor i think u knew that tho idk wat i am saying anymore

**Comment by adfhsakfhas** [comment]
also how would I use your kahoot-searcher module with this I would love to know also no wonder I couldn't get it I am just a little brain dead

**Comment by adfhsakfhas** [comment]
basically I was looking through your past issues to see if I could find an example yet I failed but
I did find a snippet of code I think could have been useful. I encorporated it and it don't work tho it was written by you so I am not sure 
client.on("questionStart", (question) => {
        **const choices = quiz.questions[question.questionindex].choices;**//this is ur code i ummmm borrowed lol
        console.log(choices);
        console.log("A new question has started, answering a random answer.");
        answerNo = randomInt(0, 4);
        
        question.answer(answerNo);
        console.log(answerNo, "  is what I picked I am cracked lol");
    });

**Comment by adfhsakfhas** [comment]
client.on("questionStart", (question) => {
        const choices = quiz.questions[question.questionindex].choices;
        console.log(choices);
        console.log("A new question has started, answering a random answer.");
        answerNo = randomInt(0, 4);
        
        question.answer(answerNo);
        console.log(answerNo, "  is what I picked I am cracked lol");
    });

**Comment by adfhsakfhas** [comment]
ok its not going to look nice

**Comment by adfhsakfhas** [comment]
I am going to die
nothing works

**Comment by adfhsakfhas** [comment]
also I didn't know how to tag it as a question at the time.

**Comment by theusaf** [comment]
Using just `kahoot.js-updated` will not let you get the correct answers unless you are playing a Kahoot challenge. To get the correct answers, you will need to use other things, such as `kahoot-search` and get the quiz name from the user in order to find the quiz. Then you can get the correct answers.

**Comment by adfhsakfhas** [comment]
I see how u have to use kahoot search thanks and I am to laazY TO implement it also sorry for wierd captilazation i a m on mt phone and this hard
