### ISSUE TITLE
Help getting the bot to answer questions 

### ISSUE THREAD

**Issue by adfhsakfhas** [theusaf/kahoot.js-updated#65]
Read underneath
|
v

**Comment by adfhsakfhas** [comment]
https://github.com/adfhsakfhas/Hello

**Comment by adfhsakfhas** [comment]
thanks in advance

**Comment by adfhsakfhas** [comment]
change the data.json values to some that will work then try it and you get the error header_token

**Comment by adfhsakfhas** [comment]
also this does not answer the questions isn't amazing also explain why it don't work it will help me get better 
async function version1(){
    
    //console.log(typeof(stuff))
    //console.log(stuff)
    //console.log()
    //console.log(typeof(stuff.Pin))
    //console.log(stuff.Name)
    //console.log(stuff.No)
    //console.log(stuff.Pin)
    //KahootPin = stuff.Pin;
    //nameOfBots = stuff.Name;
    //total = stuff.No;
    //total = parseInt(total)

    //KahootPin = parseInt(KahootPin)
    //console.log(typeof(total), typeof(KahootPin))
    n = 1000
    x = 0;
    let i = 0;
  const a = setInterval(()=>{
    const j = i + 1;
    const {client,event} = Kahoot.join("1781941",stuff.Name + "-" + (++i));
    event.then(()=>{
      console.log("Bot " + j + " joined!");
    }).catch((e)=>{
      console.log("Bot " + j + " failed to join:");
      console.log(e);
      client.leave();
    });
    client.on("quizStart", (quiz) => {
        console.log("The quiz has started! The quiz's name is:", quiz.name);
    });
    client.on("questionStart", (question) => {
        console.log("A new question has started, answering a random answer.");
        answerNo = randomInt(0, 4)
        question.answer(answerNo);
        console.log(answerNo, "  is what I picked I am cracked lol")
        setTimeout(100)
    });
    client.on("questionEnd", (question) =>{
        console.log("question Ended")
    });
    client.on("quizEnd", () => {
        console.log("The quiz has ended.");
    });
    client.on("Disconnect",(reason)=>{
      console.log("Bot " + j + " disconnected: " + reason);
    });
    if(i >= n){
      clearInterval(a);
    }
  },35);
  
};
thanks again idk i am not amazing at coding

**Comment by adfhsakfhas** [comment]
`async function version1(){
    //var total = prompt('How many friends Lol  ');
    console.log(typeof(stuff))
    console.log(stuff)
    console.log()
    console.log(typeof(stuff.Pin))
    console.log(stuff.Name)
    console.log(stuff.No)
    console.log(stuff.Pin)
    KahootPin = stuff.Pin;
    nameOfBots = stuff.Name;
    total = stuff.No;
    total = parseInt(total)

    //var nameOfBots = prompt('Name of friends why do i do this  ')
    //var KahootPin = prompt('Kahoot pin for friends to join  ')
    KahootPin = parseInt(KahootPin)
    console.log(typeof(total), typeof(KahootPin))
    n = 1000
    x = 0;
    let i = 0;
  const a = setInterval(()=>{
    const j = i + 1;
    const {client,event} = Kahoot.join("1781941",stuff.Name + "-" + (++i));
    event.then(()=>{
      console.log("Bot " + j + " joined!");
    }).catch((e)=>{
      console.log("Bot " + j + " failed to join:");
      console.log(e);
      client.leave();
    });
    client.on("quizStart", (quiz) => {
        console.log("The quiz has started! The quiz's name is:", quiz.name);
    });
    client.on("questionStart", (question) => {
        console.log("A new question has started, answering a random answer.");
        answerNo = randomInt(0, 4)
        question.answer(answerNo);
        console.log(answerNo, "  is what I picked I am cracked lol")
        setTimeout(100)
    });
    client.on("questionEnd", (question) =>{
        console.log("question Ended")
    });
    client.on("quizEnd", () => {
        console.log("The quiz has ended.");
    });
    client.on("Disconnect",(reason)=>{
      console.log("Bot " + j + " disconnected: " + reason);
    });
    if(i >= n){
      clearInterval(a);
    }
  },35);
  
};`

**Comment by adfhsakfhas** [comment]
dang it i am tring to make it show as code
[stuff.txt](https://github.com/theusaf/kahoot.js-updated/files/5577050/stuff.txt)
there just rename it and it has all the proper indenting

**Comment by adfhsakfhas** [comment]
okay I fixed the header_token thing but I need help with getting my bots to answer questions for some reason it looks like they are not going when client.on("questionStart", (question) =>
Cause I get no output which makes me think maybe there is a different way? or I am doing something wrong I am not sure its also possible this isn't how it works I dont know but hey any help is apriecated
thanks

**Comment by adfhsakfhas** [comment]
So bassically I need help making the bots answer the questions Here is the txt file change it to .js also a data.json file as well so u can use the script 
[stuff.txt](https://github.com/theusaf/kahoot.js-updated/files/5578958/stuff.txt)


[data.json.txt](https://github.com/theusaf/kahoot.js-updated/files/5578960/data.json.txt)

cool help me whenu can

**Comment by theusaf** [comment]
Events are case-sensitive. The question start event is “QuestionStart” and not “questionStart”

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir

**Comment by adfhsakfhas** [comment]
thanks

**Comment by adfhsakfhas** [comment]
nvm it didn't work for me can u just fix the code and leave little //comments on what changed there and why
Thanks also sorry for not being great at this I have been changing a lot of things and what reallly confuses me is I had a while loop version which had a ton of loss bots but it would answer even though the event was "questionStart" and it still works

**Comment by adfhsakfhas** [comment]
My error console log

"""
A new question has started, answering a random answer.
1   is what I picked I am cracked lol
internal/validators.js:218
    throw new ERR_INVALID_CALLBACK(callback);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received 100
    at setTimeout (timers.js:134:3)
    at Client.<anonymous> (C:\Users\[user]\Desktop\NodeJS_projects\stuff\botter\kahootBotter.js:52:9)
    at Client.emit (events.js:327:22)
    at Client._emit (C:\Users\[user]\Desktop\NodeJS_projects\stuff\botter\node_modules\kahoot.js-updated\src\kahoot.js:360:17)  
    at Object.handlers.questionStart (C:\Users\[user]\Desktop\NodeJS_projects\stuff\botter\node_modules\kahoot.js-updated\src\modules\questionStart.js:26:12)
    at Client._message (C:\Users\[user]\Desktop\NodeJS_projects\stuff\botter\node_modules\kahoot.js-updated\src\kahoot.js:342:23)
    at WebSocket.<anonymous> (C:\Users\[user]\Desktop\NodeJS_projects\stuff\botter\node_modules\kahoot.js-updated\src\kahoot.js:297:14)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\[user]\Desktop\NodeJS_projects\stuff\botter\node_modules\ws\lib\websocket.js:825:20)    at Receiver.emit (events.js:315:20) {
  code: 'ERR_INVALID_CALLBACK'
}
"""
code:

[kahootBotter copy.js.txt](https://github.com/theusaf/kahoot.js-updated/files/5580421/kahootBotter.copy.js.txt)

data edit pin or all values:

[data.json.txt](https://github.com/theusaf/kahoot.js-updated/files/5580405/data.json.txt)

**Comment by botgriefer** [comment]
//I am guessing your making a bot. Here is an example to use:
const Kahoot = require("kahoot.js-updated");

const PIN = "803015";
const numOfBots = 2;
const nameList = ["Bot1","Bot2","Bot3"];

let bots = [];

main();

function getRandomInt(max) {
    return Math.floor(Math.random() * Math.floor(max));
}

function joined(index){
    console.log(nameList[index].toString() +" Joined!");
}

function disconnect(reason, index){
    console.log(nameList[index].toString() + " Disconnected: " + reason);
}

function quesstart(question, index){
    let answer = getRandomInt(question.quizQuestionAnswers[question.questionIndex]);
    bots[index].answer(answer);
    console.log(nameList[index].toString() + " answered => " + answer);
}

function pod(podiumMedalType, index){
    if(podiumMedalType.podiumMedalType != null){
        console.log(nameList[index].toString() + " got: " + podiumMedalType.podiumMedalType);
    }
    bots[index].leave();
}

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function main(){
    for(let i = 0; i < numOfBots && i < nameList.length; i++){
        bots[i] = new Kahoot({modules: {extraData: false,feedback: false,teamAccept: false}});//decrease memory use
        bots[i].join(PIN,nameList[i]).catch(err => {
            //console.log(err);
            console.log(nameList[i].toString() + " Failed to join: " + err.description || err.status);
        });
        bots[i].on("Joined",() => joined(i));
        bots[i].on("Disconnect",(reason) => disconnect(reason, i));
        bots[i].on("QuestionStart",(question) => quesstart(question, i));        
        bots[i].on("Podium",(podiumMedalType) => pod(podiumMedalType, i));
        await sleep(50);
    }
}

**Comment by theusaf** [comment]
To answer your question @adfhsakfhas, you used the code `setTimeout(100)` which is invalid.
`setTimeout` works like this: `setTimeout(function,time)`.

You can probably just remove that line.

Also, check the code sent by botgriefer, it might help.

**Comment by adfhsakfhas** [comment]
Thank u it is all working now
