### ISSUE TITLE
GET_END_EVT_ERR

### ISSUE THREAD

**Issue by codingMASTER398** [theusaf/kahoot.js-updated#66]
**Describe the bug**
I have the kahoot bot running and working, but whenever a bot finishes a questions it prints in the console "GET_END_EVT_ERR"

**To Reproduce**
I have no idea, try to check if the bot got it correct?

**Expected behavior**
Not print GET_END_EVT_ERR

**Screenshots**
![image](https://user-images.githubusercontent.com/55938439/100708516-92a71580-3400-11eb-91f2-cb224f0a5195.png)

**System (please complete the following information):**
 - OS: Windows
 - Build 19042

**Comment by theusaf** [comment]
`GET_END_EVT_ERR` is an error logged by the old (v 1.x.x) version of kahoot.js-updated. Make sure you upgrade to the latest version using `npm i kahoot.js-updated@latest`
