### ISSUE TITLE
Any way to get quiz name?

### ISSUE THREAD

**Issue by F1R3L1GHT** [theusaf/kahoot.js-updated#67]
Any way to get quiz name? ima make a kahoot hack lmfao

**Comment by F1R3L1GHT** [comment]
o wait, u alr made it, kahoot-win.herokuapp.com

**Comment by F1R3L1GHT** [comment]
*kinda wanna buy the source code lmfao*

**Comment by theusaf** [comment]
Great news! A source of Kahoot Winner is open. (Check my repositories)
Anyway, there is no way to get the quiz name automatically. You have to ask the user for it.

**Comment by F1R3L1GHT** [comment]
wow, tysm!
