### ISSUE TITLE
header_token

### ISSUE THREAD

**Issue by codingMASTER398** [theusaf/kahoot.js-updated#71]
**Describe the bug**
Bots don't join and it just says "Failed to join: header_token"

**To Reproduce**
I don't really know.

**Expected behavior**
For the bots to join

**Screenshots**
![image](https://user-images.githubusercontent.com/55938439/103191515-63b19000-4929-11eb-9ba0-517bfe8973df.png)

**System (please complete the following information):**
 - OS: Windows 10
 - Version: Latest

**Additional context**
idk

**Comment by codingMASTER398** [comment]
nvm i fixed it

**Comment by SakizciAdam** [comment]
> nvm i fixed it

Please tell me how did you fix it!
