### ISSUE TITLE
Unhandled promise rejection warning: #<object>

### ISSUE THREAD

**Issue by codingMASTER398** [theusaf/kahoot.js-updated#72]
**Describe the bug**
The bot used to join but now just says Unhandled promise rejection warning: #<object> when trying to join.

**My code**
`client.join(PIN, "well hello there").catch();`
it is inside a setTimeout

**Expected behavior**
for the bot to join

**Screenshots**
![image](https://user-images.githubusercontent.com/55938439/103192276-39150680-492c-11eb-9f36-1215146f1954.png)

**Comment by theusaf** [comment]
I’m not sure, but I believe this is because you didn’t supply a function in the .catch(). The object should explain why the bot failed to join.

Sent over the interblag from a GUI.
https://github.com/theusaf
https://shortr.github.io/?llorkcir

**Comment by theusaf** [comment]
Closed due to inactivity, unable to reproduce. Likely caused due to user error.
