### ISSUE TITLE
Fix for pkg

### ISSUE THREAD

**Issue by codingMASTER398** [theusaf/kahoot.js-updated#73]
**Describe the bug**
With the newest version of this, when compiling to pkg, client.on("QuestionReady") does not fire.

**To Reproduce**
Make a bot that uses question ready or question start and compile it to pkg.
It should not answer the question

**System (please complete the following information):**
 - OS: Windows 10
 - Version: latest

**Additional context**
I just spent 3 days working on this and it does not work in pkg please help

**Comment by theusaf** [comment]
> However your code may have require(variable) calls (so called non-literal argument to require) or use non-javascript files (for example views, css, images etc).
> Such cases are not handled by pkg. So you must specify the files - scripts and assets - manually in pkg property of your package.json file.

Current solution:
Add the following to `package.json`:
```json
"pkg": {
  "scripts": "node_modules/kahoot.js-updated/src/*/*.js"
},
"bin": "index.js"
```
Tested on Mac. Node14.

Currently checking to see if this can be added to the main module or not.
