### ISSUE TITLE
Cannot Make It auto Answer Correctly

### ISSUE THREAD

**Issue by Justiniscoding** [theusaf/kahoot.js-updated#74]
I am trying to make my bot auto answer correctly and nothing works.
My program looks like this:

const Kahoot = require("kahoot.js-updated");
const client = new Kahoot();
const PIN = prompt("What Is Your Game Pin?  >>");
const NAME = prompt("What Will Your Name Be?  >>");
console.log("Joining Kahoot!");
client.join(PIN,NAME);
client.on("Joined", () => {
  console.log("I Joined The Kahoot!");
});
client.on("QuizStart", () => {
  console.log("The Quiz Has Started!");
});
client.on("QuestionStart", question => {
  console.log("A New Question Has Started, Answering The Correct Answer.");
    const choices = Question.choices;
    console.log(choices);
  });
client.on("QuizEnd", () => {
  console.log("The quiz has ended.");
});

**Comment by theusaf** [comment]
kahoot.js-updated simply interacts with the Kahoot API and doesn't get correct answers. In your code, you aren't even answering anything, just logging `Question.choices`, which will be undefined. You can only access the correct answers in challenges.

To answer correctly in regular Kahoot games, you need to search for the quiz the client is in and filter through stuff to find the correct answer

**Comment by Justiniscoding** [comment]
Could you show me an example

**Comment by theusaf** [comment]
https://github.com/theusaf/kahoot-winner
- A really big example, but it is an example.

**Comment by Justiniscoding** [comment]
Is kahoot.js the main file?

**Comment by theusaf** [comment]
Yes

**Comment by Justiniscoding** [comment]
Is It Possible To Get A List Of The Questions Before The Kahoot Starts?

**Comment by Justiniscoding** [comment]
So I can tell my bot what the answer is for the current question?

**Comment by theusaf** [comment]
If you can fetch the quiz the client is in using various filtering methods, yes you can tell the bot the correct answer.
