### ISSUE TITLE
Failed to join: undefined

### ISSUE THREAD

**Issue by codingMASTER398** [theusaf/kahoot.js-updated#76]
Users of kahootflood.weebly.com have been getting "Failed to join: undefined" for a while. What are the causes of it?

_by the way, sorry i broke your antibot_

**Comment by theusaf** [comment]
Looking at the code, it could be:
- rejection at HandshakeFailed, I didn't provide a description there.
- missing room, I also didn't provide a description there.

I'll send a fix soon.

Also, about the antibot thing, don't worry. I'll eventually figure out a way to block them!

**Comment by codingMASTER398** [comment]
Okay thanks.

Also, about the antibot thing, don't worry. I'll eventually figure out a way to get through it again just when you think you blocked em!
