### ISSUE TITLE
Client URLS

### ISSUE THREAD

**Issue by awesomecoder3000** [theusaf/kahoot.js-updated#77]
Hello, I was wondering how you script sends data to KAHOOT!, like where GET or POST requests are sent from and to.

**Comment by awesomecoder3000** [comment]
Also, maybe how you decode the tokens in more detail

**Comment by theusaf** [comment]
Good question. Most of your answers can be found at https://kahoot.js.org/class/client

**Comment by awesomecoder3000** [comment]
Thanks. I also did some more research to find out more. This is really
amazing work!
Aviv!

**Comment by awesomecoder3000** [comment]
One last thing, where in the part of the script that makes the websocket connection located?

**Comment by awesomecoder3000** [comment]
Nevermind, found it
