### ISSUE TITLE
Not working with react.

### ISSUE THREAD

**Issue by IkBenOlie5** [theusaf/kahoot.js-updated#79]
When I import it using
const Kahoot = require("kahoot.js-updated");
and run it with react, it will give me this error:
https://pastebin.com/syXiRQuG

now i fixed it by making the react stuff connect to an external websocket server which joins the game and then sends the information back to the react app. but this isn't the most beautiful solution.
using macos mojave
kahoot.js-updated version 2.3.4

**Comment by theusaf** [comment]
This doesn't seem to be an issue with kahoot.js-updated. It looks like your system ran out of memory while trying to build something.

**Comment by IkBenOlie5** [comment]
yes but when i try to do this without importing kahoot.js-updated it works perfectly fine

**Comment by theusaf** [comment]
Hmm. Maybe https://github.com/facebook/create-react-app/issues/8096 is the cause of this?

**Comment by theusaf** [comment]
What other dependencies does your program use? Does react still fail to build if you only have kahoot.js-updated imported?

**Comment by IkBenOlie5** [comment]
I don't really use any other depencencies apart from ws for a websocket server, and in my App.js file all I import are components and useEffect, useState...
https://github.com/IkBenOlie5/kahoot-client/tree/master

ans I don't really understand why adding a line:
const Client = require('kahoot.js-updated')
would make it run out of memory.
(also tried importing some other packages, but they work fine)

**Comment by theusaf** [comment]
Do you know if this error happens in version 1.4.27?

**Comment by theusaf** [comment]
Did some testing. Appears to be an issue with the user-agents module.

**Comment by IkBenOlie5** [comment]
And how can I fix it?

**Comment by IkBenOlie5** [comment]
<img width="273" alt="Schermafbeelding 2021-02-07 om 10 16 27" src="https://user-images.githubusercontent.com/73174454/107142233-aa81a500-692d-11eb-9c5a-dfb7d74633b0.png">
when I try and run the build command like this:
react-scripts --expose-gc --max-old-space-size=8192 build
it doesn't error but it gets stuck, I let it load for like 2 hours and nothing happened and it takes up very much ram
