### ISSUE TITLE
Question Events and question.answer don't work as expected all the time

### ISSUE THREAD

**Issue by TheNoob27** [theusaf/kahoot.js-updated#8]

**Comment by TheNoob27** [comment]
i know this might not be easy but eh lol
i’ve looked through all the properties of the question object, but there was no question name and i really need that xd
also the time left is always 5

**Comment by theusaf** [comment]
The question does not have a name. Kahoot doesn't supply that information (for relatively obvious reasons)

I do not understand what you mean by "the time left is always 5"

If you are looking for the quiz name, use the quiz object for that.

**Comment by theusaf** [comment]
However, you can get the answers after each question, so you could use Kahoot's API to search for the quizzes of the same name. Then you could filter them by the answers you receive.

**Comment by TheNoob27** [comment]
by the time left, i mean when a question is received, one of the properties is timeLeft, which is the same when the question starts. Now that i think about it, both of them are a question object so it makes sense so that doesn’t really matter.

i know how to get the quiz name, it’s just for the questions that i need help with. Why is it not supplied for “obvious reasons”? And how would i go about with the kahoot api and finding the questions anyway?

**Comment by TheNoob27** [comment]
oops

**Comment by TheNoob27** [comment]
how would i use the kahoot api to get the question name

**Comment by TheNoob27** [comment]
hello? 
;-;

**Comment by theusaf** [comment]
Sorry for the late reply.

The question name is not given to the client because the client (on the website at least) has no need for it. Plus it would make bots have a huge advantage over real players. Even the quiz name is not really needed but it is included for some random reason.

As for the filtering, Kahoot has a search API (I forget the URL) but you can use my package "kahoot-search" to do it. 

Then you filter the search using something like `results.filter(obj=>{return obj.name == session.quiz.name});` (this code may be wrong)

After each question, you are given the answers, which allows you to filter the quizzes even more:
```js
possibleResults.filter(a=>{
  return a.answers.filter(b=>{
    return b.choice == question.answer && b.correct;
  }).length;
});
```

Do note that the code in this message may not be correct as it is being typed on mobile.

**Comment by TheNoob27** [comment]
thank you

but just one thing, is possibleResults a variable that you defined something as, or a property?

**Comment by theusaf** [comment]
Possible results is a variable defined by myself as an example. It stores the  quiz results from the first filter (by name) and then is used to filter even more using the answers sent to the client.

**Comment by TheNoob27** [comment]
ok thanks. i’ll try it now!

**Comment by TheNoob27** [comment]
thank you so much, i figured it out, but could you maybe check the questionSubmit event, because that is never emitted for me. This may be because of the api but ### oh well lol
also, `question.answer()` doesn’t always work.

one last question, are all the properties in all the objects all that is provided by kahoot?

**Comment by theusaf** [comment]
I'll take a look at it, but it is certainly very strange. I can sometimes reproduce the issue, and sometimes I cannot...

**Comment by TheNoob27** [comment]
it’s all right, you’re still accomplishing more than what i could ever lol

**Comment by TheNoob27** [comment]
> thank you so much, i figured it out, but could you maybe check the questionSubmit event, because that is never emitted for me. This may be because of the api but
> 
> ### oh well lol
> also, `question.answer()` doesn’t always work.
> 
> one last question, are all the properties in all the objects all that is provided by kahoot?

 the questionSubmit for whatever reason emit for the first time (that i know of)
it seems like it’s random also.
but the event isn’t as important to me than the answer function sometimes not working xd

**Comment by TheNoob27** [comment]
how does <client>.sendingAnswer work, because i tried using it to send an answer if it wasn’t sending one after the first function was called

**Comment by theusaf** [comment]
.sendingAnswer appears to be an unused variable that gets set to true when sending the answer and false when it was sent successfully.

I believe the issue lies within the answer submit packet. I will do some testing later.

**Comment by TheNoob27** [comment]
ok thanks

guess i’ll try a while true loop and break everything :D

**Comment by TheNoob27** [comment]
ok that was a bad idea

**Comment by TheNoob27** [comment]
any luck?
sorry if i’m just bothering you too much xd

**Comment by theusaf** [comment]
I found a temporary fix, but I don't like it. It seems to send too many messages than it really needs to.
