### ISSUE TITLE
Unfortunately still not working with react...

### ISSUE THREAD

**Issue by IkBenOlie5** [theusaf/kahoot.js-updated#81]
Unfortunately still not working with react...
When I ran it it this time didn't error when building/starting it. you can't see the traceback until you go onto the page.

This even happened with a App.js file like this:
```
const Client = require("kahoot.js-updated");

function App() {
  return <div>hi</div>;
}

export default App;
```

also, when I ran it it errors with me needing to install a module called http2, after I install it, run the npm start and go to the page I get this error: 
https://pastebin.com/Ya6XrfuH
and the console warns me about this:
```
Compiled with warnings.

./node_modules/http2/lib/protocol/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/keyv/src/index.js
Critical dependency: the request of a dependency is an expression

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

```

ps I'm sorry to have so many errors, I rlly like this module so keep up the great work <3 ;)

**Comment by theusaf** [comment]
Might be fixed in the browser branch of this repo? Let me know if it works for you.

**Comment by IkBenOlie5** [comment]
Sorry pretty new to react, but how would you place it inside your react project?

**Comment by theusaf** [comment]
In this case, you would just add it to your `index.html` file.

**Comment by theusaf** [comment]
https://www.pluralsight.com/guides/how-to-use-a-globally-defined-script-inside-a-react-component Might be helpful

**Comment by IkBenOlie5** [comment]
I no longer get that error, but how would the client constructor class be called?
i tried window.Client() and many more.

**Comment by theusaf** [comment]
It should be window.KahootClient()

**Comment by IkBenOlie5** [comment]
well now the constructor class is right but it gives me this error
```
TypeError: can't convert undefined to object
(anonymous function)
http://localhost:3000/:45:22946
onSubmit
src/App.js:45

  42 | e.preventDefault();
  43 | 
  44 | if (gamePin.length > 0 && nickname.length > 0) {
> 45 |   setBot(new window.KahootClient());
     | ^  46 |   let success = true;
  47 |   const join = async () => {
  48 |     setGamePin(parseInt(gamePin));
```

it says it can't convert undefined to object but when I change the useState to something else it still gives me the same error

**Comment by theusaf** [comment]
Does the current version work now?

**Comment by IkBenOlie5** [comment]
with the browser version yes but i get that other error now ^^

**Comment by theusaf** [comment]
I just tested it on my own computer, that error isn't appearing for me. It might be an issue in your code?

**Comment by IkBenOlie5** [comment]
this is the repo https://github.com/IkBenOlie5/kahoot-client

**Comment by theusaf** [comment]
Your repo doesn't appear to be using the latest kahoot.js-updated browser code.

**Comment by IkBenOlie5** [comment]
I used the minified one but i can try using the other one

**Comment by IkBenOlie5** [comment]
when using the original one everything does work, but then it spits these warnings in the console:
```
Attempt to set a forbidden header was denied: Origin kahoot.js:1006:12
Attempt to set a forbidden header was denied: Referer kahoot.js:1006:12
```
and then fails and stops joining
(the kahoot.js file is just the script, and this also occurs when just having the code inside script tags)

**Comment by theusaf** [comment]
Those warnings are fine to ignore. Browsers are not allowed to set those headers. This is why it says you will almost certainly need to use the proxy option:

Example:
```js
const bot = new KahootClient({
  proxy: (options)=>{
    options.host = "corsproxy.example.com";
    return options;
  }
});
```
This is an example, you will have to set up a proxy to proxy the HTTP requests.

**Comment by IkBenOlie5** [comment]
could i use a free one like https://cors-anywhere.herokuapp.com ?

**Comment by theusaf** [comment]
Yes, you can use cors-anywhere.herokuapp.com. The reason kahoot doesn't support CORS is that they probably don't want people making kahoot bots from any website on the internet.

The reason your code above is not working is that cors anywhere works like this:
`https://cors-anywhere.herokuapp.com/https://kahoot.it/reserve/session/test`

Your current code does this:
`https://cors-anywhere.herokuapp.com/reserve/session/test`

You should log what `options` is and edit it so it will become the first link instead. (Set `options.path` to the old 
`options.protocol` plus "//" plus `options.host` plus the `options.path`.

**Comment by theusaf** [comment]
Also, note that cors-anywhere is very limited and may no longer be an open proxy: https://github.com/Rob--W/cors-anywhere/issues/301

**Comment by IkBenOlie5** [comment]
when this is the path:

path: "https://api.allorigins.win/get?url=https://kahoot.it/reserve/session/1672843/?1613116265702"

it does work when i manually go there, but not when i use it as the options
it switched from corsanywhere to allorigins

**Comment by theusaf** [comment]
Your current code is this:
```js
const bot = new window.KahootClient({
  proxy: (options) => {
    options.path = "https://api.allorigins.win/get?url=https://kahoot.it" +options.path;
    console.log(options);
    return options;
  }
});
```
The result of this is the client fetching from:
`https://kahoot.it/https://api.allorigins.win/get?url=https://kahoot.it/...`

It should probably be:
```js
const bot = new window.KahootClient({
  proxy: (options) => {
    options.path = "/get?url=https://kahoot.it" +options.path;
    options.host = "api.allorigins.win"
    console.log(options);
    return options;
  }
});
```

**Comment by IkBenOlie5** [comment]
when i use your code it still times times out:
```
description: "Request failed or timed out."
```

**Comment by theusaf** [comment]
This is because allorigins.win responds in various formats that are not supported by kahoot.js-updated.
You should find another one or create your own proxy.

I am closing this issue as I was able to get this to work in the browser using a custom proxy server using similar code already mentioned here. Feel free to continue the discussion here or in a discussion page.

**Comment by IkBenOlie5** [comment]
when hosting my own version of cors-anywhere it works tysmmmmmmmm!!!!!!!!!!
