### ISSUE TITLE
well now the constructor class is right but it gives me this error

### ISSUE THREAD

**Issue by Olivier-Berg** [theusaf/kahoot.js-updated#83]
well now the constructor class is right but it gives me this error
```
TypeError: can't convert undefined to object
(anonymous function)
http://localhost:3000/:45:22946
onSubmit
src/App.js:45

  42 | e.preventDefault();
  43 | 
  44 | if (gamePin.length > 0 && nickname.length > 0) {
> 45 |   setBot(new window.KahootClient());
     | ^  46 |   let success = true;
  47 |   const join = async () => {
  48 |     setGamePin(parseInt(gamePin));
```

it says it can't convert undefined to object but when I change the useState to something else it still gives me the same error

_Originally posted by @IkBenOlie5 in https://github.com/theusaf/kahoot.js-updated/issues/81#issuecomment-776803652_

**Comment by IkBenOlie5** [comment]
wow oops
