### ISSUE TITLE
wshandler sends too many messages during the setup process

### ISSUE THREAD

**Issue by theusaf** [theusaf/kahoot.js-updated#9]

**Comment by theusaf** [comment]
This applies to the github version 1.1.8

**Comment by TheNoob27** [comment]
well for me is just doesn’t work

it sends the error: `(node:11379) UnhandledPromiseRejectionWarning: Error: Cannot find module './lib/websocket'`

**Comment by TheNoob27** [comment]
github version btw

**Comment by theusaf** [comment]
You might have executed your code in the wrong directory. Anyways, the bug is fixed.
